services:
  dfs-frontend:
    image: dfs-frontend
    build:
      context: frontend/.
      target: service
    networks:
      - app_network

  dfs-api:
    image: dfs-api
    build:
      context: api/.
      target: service
    networks:
      - app_network

  dfs-orchestration:
    image: dfs-orchestration
    build:
      context: system/orchestrator/.
      target: service
    networks:
      - app_network

  dfs-salary-scraper:
    image: dfs-salary-scraper
    build:
      context: system/salary-scraper/.
      target: service
    networks:
      - app_network

  dfs-projection-scraper:
    image: dfs-projection-scraper
    build:
      context: system/projection-scraper/.
      target: service
    networks:
      - app_network

  selenium-web-driver:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - app_network

networks:
  app_network:
    name: dfs_optimizer_network
    driver: overlay
    attachable: true
