services:
  selenium-web-driver:
    image: selenium/standalone-chrome:latest
    container_name: selenium-web-driver
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - web_driver_network

  salary-scraper:
    image: salary-scraper
    container_name: salary-scraper
    volumes:
      - ".:/app"
    depends_on:
      - selenium-web-driver
    networks:
      - web_driver_network

networks:
  web_driver_network:
    name: salary_web_scraper_network
    attachable: true
  